name: Go CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25' # Projede kullandığın Go versiyonuna göre ayarla

    - name: Download Dependencies
      run: go mod tidy

    - name: Build Code
      run: go build ./...

    - name: Static Analysis
      run: go vet ./...

    - name: Check Code Formatting
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "code must tobe formatted. 'gofmt -w .' is working."
          exit 1
        fi
